[package]
name = "back-end"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1.37", features = ["full"] }
tower = "0.4"

redis = { version = "0.25", features = ["tokio-comp"] }